# Generated by Django 5.0.6 on 2024-06-19 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('exercise_id', models.AutoField(primary_key=True, serialize=False)),
                ('exercise_name', models.CharField(max_length=255, verbose_name='Exercise Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sets',
            fields=[
                ('set_id', models.AutoField(primary_key=True, serialize=False)),
                ('set_number', models.IntegerField()),
                ('reps', models.IntegerField()),
                ('weight', models.FloatField()),
                ('rest_duration', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trackWorkouts.exercises')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutPlans',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('plan_name', models.CharField(max_length=255, verbose_name='Workout Plan Name')),
                ('plan_description', models.TextField(verbose_name='Workout Plan Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trackWorkouts.users')),
            ],
        ),
        migrations.CreateModel(
            name='Workouts',
            fields=[
                ('workout_id', models.AutoField(primary_key=True, serialize=False)),
                ('workout_name', models.CharField(max_length=255, verbose_name='Workout Name')),
                ('date', models.DateField()),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trackWorkouts.workoutplans')),
            ],
        ),
        migrations.AddField(
            model_name='exercises',
            name='workout_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trackWorkouts.workouts'),
        ),
    ]
