# Generated by Django 5.0.6 on 2024-06-20 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackWorkouts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Exercises',
            new_name='Exercise',
        ),
        migrations.RenameModel(
            old_name='Sets',
            new_name='Set',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
        migrations.RenameModel(
            old_name='Workouts',
            new_name='Workout',
        ),
        migrations.RenameModel(
            old_name='WorkoutPlans',
            new_name='WorkoutPlan',
        ),
    ]
